#!/bin/bash

# Installation script.

# Default:
#   INSTALL_LOC=/opt                        # installation location
#   SERVICE_LOC=/etc/cron.hourly/           # service location
#   CMD_LOC=/usr/local/bin/                 # command location
#
# Execute:
#   ./INSTALL
# or change the installation location:
#   INSTALL_LOC=/home ; SERVICE_LOC=/etc/cron.daily ; ./INSTALL

INSTALL_DIR=${INSTALL_LOC:-/opt}/hosts-monitor
SERVICE=${SERVICE_LOC:-/etc/cron.hourly}/hosts-monitor-service
CMD=${CMD_LOC:-/usr/local/bin}/hosts-monitor

printf "%s\n" ">>> Install hosts-monitor in $INSTALL_DIR..."

( \
sed -i "s/INSTALL_DIR=.*/INSTALL_DIR=${INSTALL_DIR//\//\\/}/g" hosts-monitor
sed -i "s/INSTALL_DIR=.*/INSTALL_DIR=${INSTALL_DIR//\//\\/}/g" bin/profile
sed -i "s/SERVICE=.*/SERVICE=${SERVICE//\//\\/}/g" bin/profile
sed -i "s/CMD=.*/CMD=${CMD//\//\\/}/g" bin/profile

sudo cp -r . $INSTALL_DIR
sudo ln -s $INSTALL_DIR/service/hosts-monitor-service $SERVICE
sudo ln -s $INSTALL_DIR/hosts-monitor $CMD

. bin/profile
test -d $REPORT_LOC || mkdir -p $REPORT_LOC
) && printf "\033[32m%s\033[0m\n" "Setup successfully."
