#!/bin/bash

INSTALL_DIR=/opt

echo ">>> Install hosts-monitor in $INSTALL_DIR..."
sudo cp -r ../hosts-monitor $INSTALL_DIR
sudo ln -s $INSTALL_DIR/bin/hosts-monitor /usr/local/bin/hosts-monitor
sudo ln -s $INSTALL_DIR/rc/hosts-protect  /etc/cron.hourly/
echo "Setup successfully!"
