#!/bin/bash

# Execute:
#   ./uninstall

. bin/profile
( \
read -p "Backup reports ? [Y/n] " ans
if [[ $ans =~ ^[yY]*$ ]]; then 
    read -p "     backup to ? [$HOME/hosts-monitor-reports] " bak_folder
    bak_folder=${bak_folder:-$HOME/hosts-monitor-reports}
    test -d $bak_folder || mkdir -p $bak_folder
    cp $report* $bak_folder
fi
sudo rm $SERVICE
sudo rm $CMD
sudo rm -r -I $INSTALL_DIR
) && printf "\033[31m%s\033[0m\n" "Uninstall completely."
